-- Global values for the sake of the user.

-- SOLAR SYSTEM GRAVITY
GRAVSYSTEM_SUN_GRAVITY        = 273.7
GRAVSYSTEM_MERCURY_GRAVITY    = 3.7
GRAVSYSTEM_VENUS_GRAVITY      = 8.87
GRAVSYSTEM_EARTH_GRAVITY      = 9.80665
GRAVSYSTEM_MOON_GRAVITY       = 1.6249
GRAVSYSTEM_MARS_GRAVITY       = 3.7
GRAVSYSTEM_JUPITER_GRAVITY    = 24.79
GRAVSYSTEM_SATURN_GRAVITY     = 10.44
GRAVSYSTEM_URANUS_GRAVITY     = 8.87
GRAVSYSTEM_NEPTUNE_GRAVITY    = 11.15
GRAVSYSTEM_PLUTO_GRAVITY      = 0.6

-- SPECIAL GRAVITY
GRAVSYSTEM_SAGITTARIUS_A_GRAVITY = GRAVSYSTEM_EARTH_GRAVITY * 361000